name: ultsukulu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.0.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  http: ^1.5.0
  flutter_pdfview: ^1.3.2
  path: ^1.8.0
  path_provider: ^2.0.11
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/questions/
    - assets/sounds/
    - assets/icons/
    - assets/pdfs/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/logo.png"
  windows:
    generate: true
    image_path: "assets/icons/logo.png"
  macos:
    generate: true
    image_path: "assets/icons/logo.png"
