// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoYbr1jNhyWXNofoqwdHKYfu2VLVvoSkk',
    appId:
        '1:646738027057:web:your-web-app-id', // You'll need to add a web app in Firebase Console
    messagingSenderId: '646738027057',
    projectId: 'stk-manager-af4e4',
    authDomain: 'stk-manager-af4e4.firebaseapp.com',
    storageBucket: 'stk-manager-af4e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoYbr1jNhyWXNofoqwdHKYfu2VLVvoSkk',
    appId: '1:646738027057:android:f62cd870265ed343fdeb10',
    messagingSenderId: '646738027057',
    projectId: 'stk-manager-af4e4',
    storageBucket: 'stk-manager-af4e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoYbr1jNhyWXNofoqwdHKYfu2VLVvoSkk',
    appId:
        '1:646738027057:ios:your-ios-app-id', // You'll need to add an iOS app in Firebase Console
    messagingSenderId: '646738027057',
    projectId: 'stk-manager-af4e4',
    storageBucket: 'stk-manager-af4e4.firebasestorage.app',
    iosBundleId: 'com.paradroid.stkmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoYbr1jNhyWXNofoqwdHKYfu2VLVvoSkk',
    appId:
        '1:646738027057:macos:your-macos-app-id', // You'll need to add a macOS app in Firebase Console
    messagingSenderId: '646738027057',
    projectId: 'stk-manager-af4e4',
    storageBucket: 'stk-manager-af4e4.firebasestorage.app',
    iosBundleId: 'com.paradroid.stkmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoYbr1jNhyWXNofoqwdHKYfu2VLVvoSkk',
    appId:
        '1:646738027057:windows:your-windows-app-id', // You'll need to add a Windows app in Firebase Console
    messagingSenderId: '646738027057',
    projectId: 'stk-manager-af4e4',
    authDomain: 'stk-manager-af4e4.firebaseapp.com',
    storageBucket: 'stk-manager-af4e4.firebasestorage.app',
  );
}
